dbt_learning:  # Make sure this matches your dbt_project.yml
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ticrbjz-fw37071
      user: MEPATEL03
      password: HelloHy@2404@##
      role: ACCOUNTADMIN
      database: dbt_db
      warehouse: dbt_wh
      schema: dev
      threads: 4
      client_session_keep_alive: False
